alter table "BOOKRECEIPTS" add ( "CRATE_ID" NUMBER (38,0) );

COMMENT ON COLUMN "BOOKRECEIPTS"."CRATE_ID" IS '' ;

alter table "POS" add ( "INVOICES_COUNT" NUMBER (38,0) );

COMMENT ON COLUMN "POS"."INVOICES_COUNT" IS '' ;
