alter table "ENRICHEDTITLES" add ( "CATEGORY1" VARCHAR2(1020) );
alter table "ENRICHEDTITLES" add ( "CATEGORY3" VARCHAR2(1020) );
alter table "ENRICHEDTITLES" add ( "CATEGORY2" VARCHAR2(1020) );

alter table "ENRICHEDTITLE_VERSIONS" add ( "CATEGORY1" VARCHAR2(1020) );
alter table "ENRICHEDTITLE_VERSIONS" add ( "CATEGORY3" VARCHAR2(1020) );
alter table "ENRICHEDTITLE_VERSIONS" add ( "CATEGORY2" VARCHAR2(1020) );
