BEGIN
  EXPAND_NEWARRIVALS_ITEMS(8);
END;

SELECT * FROM newarrivals_expanded
SELECT count(*) FROM CORELIST WHERE key_id = 4
select count(*) from newarrivals_expanded where key_id = 7

BEGIN
  DATA_PULL.PR_PULL_CORELIST_ITEMS(5);
END;

BEGIN
  DATA_PULL.PR_PULL_NEWARRIVAL_ITEMS(8);
END;

SELECT COUNT(*) FROM PROCUREMENTITEMS --36377 / 37285 / 40532 / 40968 / 41329
select 41329 - 40968 from dual
SELECT count(*) FROM PROCUREMENTITEMS WHERE po_number IS NULL
SELECT * FROM PROCUREMENTITEMS WHERE po_number IS NULL
SELECT COUNT(*) FROM ENRICHEDTITLES WHERE ISBNVALID ='N'
SELECT COUNT(*)  FROM ENRICHEDTITLES WHERE ISBNVALID IS NULL
SELECT * FROM ISBN_VALIDITY_IN_LIST
update enrichedtitles set isbnvalid=null where isbnvalid is null
SELECT * FROM ISBNS_OF_A_LI

BEGIN
  PULL_SUPPLIER(512);
END;

SELECT COUNT(*) FROM enrichedtitles where nvl(enriched,'N') = 'N'

BEGIN
  WORKLIST_GENERATOR.pr_create_corelist_wl;
END;

BEGIN
  WORKLIST_GENERATOR.PR_CREATE_NEWENTRY_WL;
END;

SELECT COUNT(*) FROM WORKLISTS -- 237 / 472
SELECT COUNT(*) FROM WORKITEMS -- 493 / 1401
delete FROM WORKLISTS -- 237 / 472
delete FROM WORKITEMS -- 493 / 1401

BEGIN
  GENERATE_POS('NENT', 8);
END;

SELECT count(*) FROM pos -- 508 / 542 / 569 / 733
SELECT * FROM PROCUREMENTITEMS WHERE PO_NUMBER IS NULL

BEGIN
  REFRESH_PO_MASTER;
END;

SELECT CURRENCY, COUNT(*) FROM PO_VIEW GROUP BY CURRENCY
SELECT COUNT(*) FROM POS WHERE copies_cnt IS NULL
SELECT CURRENCY, COUNT(*) FROM ENRICHEDTITLES WHERE ID IN (
SELECT ENRICHEDTITLE_ID FROM PROCUREMENTITEMS WHERE PO_NUMBER IN (
SELECT CODE FROM POS WHERE copies_cnt IS NULL))
GROUP BY CURRENCY
select * from pos order by rowid desc

BEGIN
  FOR i IN (
    SELECT CODE FROM pos where to_char(created_at,'DD-MON-RR') = '04-MAY-11' and code like 'NENT%' AND ID > 11953
    )
  loop
    extract_pos(i.code);
  end loop;
end;

SELECT code FROM pos 
    WHERE code NOT IN (SELECT ponumber FROM nonbookpomaster@jbclclink WHERE ponumber IS NOT NULL)
    
BEGIN
  FOR rec IN (
    SELECT code FROM pos 
    WHERE code NOT IN (SELECT ponumber FROM nonbookpomaster@jbclclink WHERE ponumber IS NOT NULL)
  )
  loop
    push_po_to_fin(rec.code);
  end loop;
end;