BEGIN
  EXPAND_NEWARRIVALS_ITEMS(4);
END;

SELECT * FROM newarrivals_expanded
select count(*) from CORELIST where key_id = 4
select count(*) from newarrivals_expanded where key_id = 4

BEGIN
  DATA_PULL.PR_PULL_NEWARRIVAL_ITEMS(4);
END;

SELECT COUNT(*) FROM PROCUREMENTITEMS --36377 / 37285
SELECT COUNT(*) FROM ENRICHEDTITLES WHERE ISBNVALID IS NULL
SELECT * FROM ISBN_VALIDITY_IN_LIST
SELECT * FROM ISBNS_OF_A_LIST

BEGIN
  ENRICH_TITLES_FROM_JBDATA;
END;

SELECT COUNT(*) FROM enrichedtitles where nvl(enriched,'N') = 'N'

BEGIN
  WORKLIST_GENERATOR.PR_CREATE_NEWENTRY_WL;
END;

SELECT COUNT(*) FROM WORKLISTS -- 237 / 472
SELECT COUNT(*) FROM WORKITEMS -- 493 / 1401

BEGIN
  GENERATE_POS;
END;

SELECT count(*) FROM pos -- 236
SELECT * FROM PROCUREMENTITEMS WHERE PO_NUMBER IS NULL

BEGIN
  REFRESH_PO_MASTER;
END;

SELECT * FROM PO_VIEW
SELECT COUNT(*) FROM POS where copies_cnt is null

BEGIN
  FOR i IN (
    SELECT CODE FROM pos WHERE TO_CHAR(CREATED_AT,'DD-MON-RR') = '25-APR-11'
    )
  loop
    extract_pos(i.code);
  end loop;
end;


