BEGIN
  EXPAND_NEWARRIVALS_ITEMS(4);
END;

SELECT * FROM newarrivals_expanded
select count(*) from CORELIST where key_id = 4
select count(*) from newarrivals_expanded where key_id = 4

BEGIN
  DATA_PULL.PR_PULL_CORELIST_ITEMS(5);
END;

BEGIN
  DATA_PULL.PR_PULL_NEWARRIVAL_ITEMS(4);
END;

SELECT COUNT(*) FROM PROCUREMENTITEMS --36377 / 37285 / 40532
SELECT count(*) FROM PROCUREMENTITEMS WHERE po_number IS NULL
SELECT * FROM PROCUREMENTITEMS WHERE po_number IS NULL
SELECT COUNT(*) FROM ENRICHEDTITLES WHERE ISBNVALID ='N'
SELECT * FROM ENRICHEDTITLES WHERE ISBNVALID IS NULL
SELECT * FROM ISBN_VALIDITY_IN_LIST
SELECT * FROM ISBNS_OF_A_LIST

BEGIN
  ENRICH_TITLES_FROM_JBDATA;
END;

SELECT COUNT(*) FROM enrichedtitles where nvl(enriched,'N') = 'N'

BEGIN
  WORKLIST_GENERATOR.pr_create_corelist_wl;
END;

BEGIN
  WORKLIST_GENERATOR.PR_CREATE_NEWENTRY_WL;
END;

SELECT COUNT(*) FROM WORKLISTS -- 237 / 472
SELECT COUNT(*) FROM WORKITEMS -- 493 / 1401
delete FROM WORKLISTS -- 237 / 472
delete FROM WORKITEMS -- 493 / 1401

BEGIN
  GENERATE_POS;
END;

SELECT count(*) FROM pos -- 508
SELECT * FROM PROCUREMENTITEMS WHERE PO_NUMBER IS NULL

BEGIN
  REFRESH_PO_MASTER;
END;

SELECT CURRENCY, COUNT(*) FROM PO_VIEW GROUP BY CURRENCY
SELECT COUNT(*) FROM POS WHERE copies_cnt IS NULL
SELECT CURRENCY, COUNT(*) FROM ENRICHEDTITLES WHERE ID IN (
SELECT ENRICHEDTITLE_ID FROM PROCUREMENTITEMS WHERE PO_NUMBER IN (
SELECT CODE FROM POS WHERE copies_cnt IS NULL))
GROUP BY CURRENCY
select * from pos order by rowid desc

BEGIN
  FOR i IN (
    SELECT CODE FROM pos where branch_id=43
    )
  loop
    extract_pos(i.code);
  end loop;
end;

SELECT code FROM pos 
    WHERE code NOT IN (SELECT ponumber FROM nonbookpomaster@jbclclink WHERE ponumber IS NOT NULL)
    
BEGIN
  FOR rec IN (
    SELECT code FROM pos 
    WHERE code NOT IN (SELECT ponumber FROM nonbookpomaster@jbclclink WHERE ponumber IS NOT NULL)
  )
  loop
    push_po_to_fin(rec.code);
  end loop;
end;