development:
  access_key_id: AKIAILA4JXNSWWDFVCLQ
  secret_access_key: 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
  bucket: dev.justbooksclc.com

production:
  access_key_id: dirty
  secret_access_key: picture
  bucket: dirty.pick
