development:
 adapter: oracle_enhanced
 database: JEOS
 username: ams
 password: ams
 encoding: utf8
 
test:
 adapter: oracle_enhanced
 database: XE
 username: ams
 password: ams

production:
 adapter: oracle_enhanced
 database: XE
 username: ams
 password: ams
