# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
 adapter: oracle_enhanced
 database: XE
 username: ams
 password: ams
 
test:
 adapter: oracle_enhanced
 database: XE
 username: ams
 password: ams

production:
 adapter: oracle_enhanced
 database: XE
 username: ams
 password: ams
