# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: oracle_enhanced
  database: XE
  username: ams
  password: ams
  cursor_sharing: similar

jbprod_development:
  adapter: oracle_enhanced
  database: XE
  username: jbprod
  password: jbprod
  cursor_sharing: similar

id_gen:
  adapter: oracle_enhanced
  database: XE
  username: id_gen
  password: id_gen
