# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
 adapter: oracle_enhanced
 database: XE
 username: bookbuy
 password: bookbuy
 
test:
 adapter: oracle_enhanced
 database: XE
 username: bookbuy
 password: bookbuy

production:
 adapter: oracle_enhanced
 database: XE
 username: bookbuy
 password: bookbuy
