production:
  solr:
    hostname: 74.86.131.195
    port: 7585
    log_level: INFO

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO

test:
  solr:
    hostname: 74.86.131.195
    port: 7585
    log_level: INFO