require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BatchesController do

  def mock_batch(stubs={})
    @mock_batch ||= mock_model(Batch, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all batches as @batches" do
      Batch.stub(:all) { [mock_batch] }
      get :index
      assigns(:batches).should eq([mock_batch])
    end
  end

  describe "GET show" do
    it "assigns the requested batch as @batch" do
      Batch.stub(:find).with("37") { mock_batch }
      get :show, :id => "37"
      assigns(:batch).should be(mock_batch)
    end
  end

  describe "GET new" do
    it "assigns a new batch as @batch" do
      Batch.stub(:new) { mock_batch }
      get :new
      assigns(:batch).should be(mock_batch)
    end
  end

  describe "GET edit" do
    it "assigns the requested batch as @batch" do
      Batch.stub(:find).with("37") { mock_batch }
      get :edit, :id => "37"
      assigns(:batch).should be(mock_batch)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created batch as @batch" do
        Batch.stub(:new).with({'these' => 'params'}) { mock_batch(:save => true) }
        post :create, :batch => {'these' => 'params'}
        assigns(:batch).should be(mock_batch)
      end

      it "redirects to the created batch" do
        Batch.stub(:new) { mock_batch(:save => true) }
        post :create, :batch => {}
        response.should redirect_to(batch_url(mock_batch))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved batch as @batch" do
        Batch.stub(:new).with({'these' => 'params'}) { mock_batch(:save => false) }
        post :create, :batch => {'these' => 'params'}
        assigns(:batch).should be(mock_batch)
      end

      it "re-renders the 'new' template" do
        Batch.stub(:new) { mock_batch(:save => false) }
        post :create, :batch => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested batch" do
        Batch.stub(:find).with("37") { mock_batch }
        mock_batch.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :batch => {'these' => 'params'}
      end

      it "assigns the requested batch as @batch" do
        Batch.stub(:find) { mock_batch(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:batch).should be(mock_batch)
      end

      it "redirects to the batch" do
        Batch.stub(:find) { mock_batch(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(batch_url(mock_batch))
      end
    end

    describe "with invalid params" do
      it "assigns the batch as @batch" do
        Batch.stub(:find) { mock_batch(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:batch).should be(mock_batch)
      end

      it "re-renders the 'edit' template" do
        Batch.stub(:find) { mock_batch(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested batch" do
      Batch.stub(:find).with("37") { mock_batch }
      mock_batch.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the batches list" do
      Batch.stub(:find) { mock_batch }
      delete :destroy, :id => "1"
      response.should redirect_to(batches_url)
    end
  end

end
