require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CurrencyratesController do

  def mock_currencyrate(stubs={})
    @mock_currencyrate ||= mock_model(Currencyrate, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all currencyrates as @currencyrates" do
      Currencyrate.stub(:all) { [mock_currencyrate] }
      get :index
      assigns(:currencyrates).should eq([mock_currencyrate])
    end
  end

  describe "GET show" do
    it "assigns the requested currencyrate as @currencyrate" do
      Currencyrate.stub(:find).with("37") { mock_currencyrate }
      get :show, :id => "37"
      assigns(:currencyrate).should be(mock_currencyrate)
    end
  end

  describe "GET new" do
    it "assigns a new currencyrate as @currencyrate" do
      Currencyrate.stub(:new) { mock_currencyrate }
      get :new
      assigns(:currencyrate).should be(mock_currencyrate)
    end
  end

  describe "GET edit" do
    it "assigns the requested currencyrate as @currencyrate" do
      Currencyrate.stub(:find).with("37") { mock_currencyrate }
      get :edit, :id => "37"
      assigns(:currencyrate).should be(mock_currencyrate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created currencyrate as @currencyrate" do
        Currencyrate.stub(:new).with({'these' => 'params'}) { mock_currencyrate(:save => true) }
        post :create, :currencyrate => {'these' => 'params'}
        assigns(:currencyrate).should be(mock_currencyrate)
      end

      it "redirects to the created currencyrate" do
        Currencyrate.stub(:new) { mock_currencyrate(:save => true) }
        post :create, :currencyrate => {}
        response.should redirect_to(currencyrate_url(mock_currencyrate))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved currencyrate as @currencyrate" do
        Currencyrate.stub(:new).with({'these' => 'params'}) { mock_currencyrate(:save => false) }
        post :create, :currencyrate => {'these' => 'params'}
        assigns(:currencyrate).should be(mock_currencyrate)
      end

      it "re-renders the 'new' template" do
        Currencyrate.stub(:new) { mock_currencyrate(:save => false) }
        post :create, :currencyrate => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested currencyrate" do
        Currencyrate.stub(:find).with("37") { mock_currencyrate }
        mock_currencyrate.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :currencyrate => {'these' => 'params'}
      end

      it "assigns the requested currencyrate as @currencyrate" do
        Currencyrate.stub(:find) { mock_currencyrate(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:currencyrate).should be(mock_currencyrate)
      end

      it "redirects to the currencyrate" do
        Currencyrate.stub(:find) { mock_currencyrate(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(currencyrate_url(mock_currencyrate))
      end
    end

    describe "with invalid params" do
      it "assigns the currencyrate as @currencyrate" do
        Currencyrate.stub(:find) { mock_currencyrate(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:currencyrate).should be(mock_currencyrate)
      end

      it "re-renders the 'edit' template" do
        Currencyrate.stub(:find) { mock_currencyrate(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested currencyrate" do
      Currencyrate.stub(:find).with("37") { mock_currencyrate }
      mock_currencyrate.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the currencyrates list" do
      Currencyrate.stub(:find) { mock_currencyrate }
      delete :destroy, :id => "1"
      response.should redirect_to(currencyrates_url)
    end
  end

end
