require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ImprintsController do

  def mock_imprint(stubs={})
    @mock_imprint ||= mock_model(Imprint, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all imprints as @imprints" do
      Imprint.stub(:all) { [mock_imprint] }
      get :index
      assigns(:imprints).should eq([mock_imprint])
    end
  end

  describe "GET show" do
    it "assigns the requested imprint as @imprint" do
      Imprint.stub(:find).with("37") { mock_imprint }
      get :show, :id => "37"
      assigns(:imprint).should be(mock_imprint)
    end
  end

  describe "GET new" do
    it "assigns a new imprint as @imprint" do
      Imprint.stub(:new) { mock_imprint }
      get :new
      assigns(:imprint).should be(mock_imprint)
    end
  end

  describe "GET edit" do
    it "assigns the requested imprint as @imprint" do
      Imprint.stub(:find).with("37") { mock_imprint }
      get :edit, :id => "37"
      assigns(:imprint).should be(mock_imprint)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created imprint as @imprint" do
        Imprint.stub(:new).with({'these' => 'params'}) { mock_imprint(:save => true) }
        post :create, :imprint => {'these' => 'params'}
        assigns(:imprint).should be(mock_imprint)
      end

      it "redirects to the created imprint" do
        Imprint.stub(:new) { mock_imprint(:save => true) }
        post :create, :imprint => {}
        response.should redirect_to(imprint_url(mock_imprint))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved imprint as @imprint" do
        Imprint.stub(:new).with({'these' => 'params'}) { mock_imprint(:save => false) }
        post :create, :imprint => {'these' => 'params'}
        assigns(:imprint).should be(mock_imprint)
      end

      it "re-renders the 'new' template" do
        Imprint.stub(:new) { mock_imprint(:save => false) }
        post :create, :imprint => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested imprint" do
        Imprint.stub(:find).with("37") { mock_imprint }
        mock_imprint.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :imprint => {'these' => 'params'}
      end

      it "assigns the requested imprint as @imprint" do
        Imprint.stub(:find) { mock_imprint(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:imprint).should be(mock_imprint)
      end

      it "redirects to the imprint" do
        Imprint.stub(:find) { mock_imprint(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(imprint_url(mock_imprint))
      end
    end

    describe "with invalid params" do
      it "assigns the imprint as @imprint" do
        Imprint.stub(:find) { mock_imprint(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:imprint).should be(mock_imprint)
      end

      it "re-renders the 'edit' template" do
        Imprint.stub(:find) { mock_imprint(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested imprint" do
      Imprint.stub(:find).with("37") { mock_imprint }
      mock_imprint.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the imprints list" do
      Imprint.stub(:find) { mock_imprint }
      delete :destroy, :id => "1"
      response.should redirect_to(imprints_url)
    end
  end

end
