require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ImprintsController do

  before(:each) do 
    @user = Factory.create(:user)
    sign_in @user
  end

  describe "GET index" do
    pending "assigns all imprints as @imprints" do
    end
  end

  describe "GET show" do
    pending "assigns the requested imprint as @imprint" do
    end
  end

  describe "GET new" do
    pending "assigns a new imprint as @imprint" do
    end
  end

  describe "GET edit" do
    pending "assigns the requested imprint as @imprint" do
    end
  end

  describe "POST create" do
    describe "with valid params" do
      pending "assigns a newly created imprint as @imprint" do
      end

      pending "redirects to the created imprint" do
      end
    end

    describe "with invalid params" do
      pending "assigns a newly created but unsaved imprint as @imprint" do
      end

      pending "re-renders the 'new' template" do
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      pending "updates the requested imprint" do
      end

      pending "assigns the requested imprint as @imprint" do
      end

      pending "redirects to the imprint" do
      end
    end

    describe "with invalid params" do
      pending "assigns the imprint as @imprint" do
      end

      pending "re-renders the 'edit' template" do
      end
    end
  end

  describe "DELETE destroy" do
    pending "destroys the requested imprint" do
    end

    pending "redirects to the imprints list" do
    end
  end

end
