require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InvoiceitemsController do

  # This should return the minimal set of attributes required to create a valid
  # Invoiceitem. As you add validations to Invoiceitem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all invoiceitems as @invoiceitems" do
      invoiceitem = Invoiceitem.create! valid_attributes
      get :index
      assigns(:invoiceitems).should eq([invoiceitem])
    end
  end

  describe "GET show" do
    it "assigns the requested invoiceitem as @invoiceitem" do
      invoiceitem = Invoiceitem.create! valid_attributes
      get :show, :id => invoiceitem.id.to_s
      assigns(:invoiceitem).should eq(invoiceitem)
    end
  end

  describe "GET new" do
    it "assigns a new invoiceitem as @invoiceitem" do
      get :new
      assigns(:invoiceitem).should be_a_new(Invoiceitem)
    end
  end

  describe "GET edit" do
    it "assigns the requested invoiceitem as @invoiceitem" do
      invoiceitem = Invoiceitem.create! valid_attributes
      get :edit, :id => invoiceitem.id.to_s
      assigns(:invoiceitem).should eq(invoiceitem)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Invoiceitem" do
        expect {
          post :create, :invoiceitem => valid_attributes
        }.to change(Invoiceitem, :count).by(1)
      end

      it "assigns a newly created invoiceitem as @invoiceitem" do
        post :create, :invoiceitem => valid_attributes
        assigns(:invoiceitem).should be_a(Invoiceitem)
        assigns(:invoiceitem).should be_persisted
      end

      it "redirects to the created invoiceitem" do
        post :create, :invoiceitem => valid_attributes
        response.should redirect_to(Invoiceitem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved invoiceitem as @invoiceitem" do
        # Trigger the behavior that occurs when invalid params are submitted
        Invoiceitem.any_instance.stub(:save).and_return(false)
        post :create, :invoiceitem => {}
        assigns(:invoiceitem).should be_a_new(Invoiceitem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Invoiceitem.any_instance.stub(:save).and_return(false)
        post :create, :invoiceitem => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested invoiceitem" do
        invoiceitem = Invoiceitem.create! valid_attributes
        # Assuming there are no other invoiceitems in the database, this
        # specifies that the Invoiceitem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Invoiceitem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => invoiceitem.id, :invoiceitem => {'these' => 'params'}
      end

      it "assigns the requested invoiceitem as @invoiceitem" do
        invoiceitem = Invoiceitem.create! valid_attributes
        put :update, :id => invoiceitem.id, :invoiceitem => valid_attributes
        assigns(:invoiceitem).should eq(invoiceitem)
      end

      it "redirects to the invoiceitem" do
        invoiceitem = Invoiceitem.create! valid_attributes
        put :update, :id => invoiceitem.id, :invoiceitem => valid_attributes
        response.should redirect_to(invoiceitem)
      end
    end

    describe "with invalid params" do
      it "assigns the invoiceitem as @invoiceitem" do
        invoiceitem = Invoiceitem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Invoiceitem.any_instance.stub(:save).and_return(false)
        put :update, :id => invoiceitem.id.to_s, :invoiceitem => {}
        assigns(:invoiceitem).should eq(invoiceitem)
      end

      it "re-renders the 'edit' template" do
        invoiceitem = Invoiceitem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Invoiceitem.any_instance.stub(:save).and_return(false)
        put :update, :id => invoiceitem.id.to_s, :invoiceitem => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested invoiceitem" do
      invoiceitem = Invoiceitem.create! valid_attributes
      expect {
        delete :destroy, :id => invoiceitem.id.to_s
      }.to change(Invoiceitem, :count).by(-1)
    end

    it "redirects to the invoiceitems list" do
      invoiceitem = Invoiceitem.create! valid_attributes
      delete :destroy, :id => invoiceitem.id.to_s
      response.should redirect_to(invoiceitems_url)
    end
  end

end
