require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ProcurementsController do

  def mock_procurement(stubs={})
    @mock_procurement ||= mock_model(Procurement, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all procurements as @procurements" do
      Procurement.stub(:all) { [mock_procurement] }
      get :index
      assigns(:procurements).should eq([mock_procurement])
    end
  end

  describe "GET show" do
    it "assigns the requested procurement as @procurement" do
      Procurement.stub(:find).with("37") { mock_procurement }
      get :show, :id => "37"
      assigns(:procurement).should be(mock_procurement)
    end
  end

  describe "GET new" do
    it "assigns a new procurement as @procurement" do
      Procurement.stub(:new) { mock_procurement }
      get :new
      assigns(:procurement).should be(mock_procurement)
    end
  end

  describe "GET edit" do
    it "assigns the requested procurement as @procurement" do
      Procurement.stub(:find).with("37") { mock_procurement }
      get :edit, :id => "37"
      assigns(:procurement).should be(mock_procurement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created procurement as @procurement" do
        Procurement.stub(:new).with({'these' => 'params'}) { mock_procurement(:save => true) }
        post :create, :procurement => {'these' => 'params'}
        assigns(:procurement).should be(mock_procurement)
      end

      it "redirects to the created procurement" do
        Procurement.stub(:new) { mock_procurement(:save => true) }
        post :create, :procurement => {}
        response.should redirect_to(procurement_url(mock_procurement))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved procurement as @procurement" do
        Procurement.stub(:new).with({'these' => 'params'}) { mock_procurement(:save => false) }
        post :create, :procurement => {'these' => 'params'}
        assigns(:procurement).should be(mock_procurement)
      end

      it "re-renders the 'new' template" do
        Procurement.stub(:new) { mock_procurement(:save => false) }
        post :create, :procurement => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested procurement" do
        Procurement.stub(:find).with("37") { mock_procurement }
        mock_procurement.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :procurement => {'these' => 'params'}
      end

      it "assigns the requested procurement as @procurement" do
        Procurement.stub(:find) { mock_procurement(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:procurement).should be(mock_procurement)
      end

      it "redirects to the procurement" do
        Procurement.stub(:find) { mock_procurement(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(procurement_url(mock_procurement))
      end
    end

    describe "with invalid params" do
      it "assigns the procurement as @procurement" do
        Procurement.stub(:find) { mock_procurement(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:procurement).should be(mock_procurement)
      end

      it "re-renders the 'edit' template" do
        Procurement.stub(:find) { mock_procurement(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested procurement" do
      Procurement.stub(:find).with("37") { mock_procurement }
      mock_procurement.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the procurements list" do
      Procurement.stub(:find) { mock_procurement }
      delete :destroy, :id => "1"
      response.should redirect_to(procurements_url)
    end
  end

end
