require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PublishersController do

  def mock_publisher(stubs={})
    @mock_publisher ||= mock_model(Publisher, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all publishers as @publishers" do
      Publisher.stub(:all) { [mock_publisher] }
      get :index
      assigns(:publishers).should eq([mock_publisher])
    end
  end

  describe "GET show" do
    it "assigns the requested publisher as @publisher" do
      Publisher.stub(:find).with("37") { mock_publisher }
      get :show, :id => "37"
      assigns(:publisher).should be(mock_publisher)
    end
  end

  describe "GET new" do
    it "assigns a new publisher as @publisher" do
      Publisher.stub(:new) { mock_publisher }
      get :new
      assigns(:publisher).should be(mock_publisher)
    end
  end

  describe "GET edit" do
    it "assigns the requested publisher as @publisher" do
      Publisher.stub(:find).with("37") { mock_publisher }
      get :edit, :id => "37"
      assigns(:publisher).should be(mock_publisher)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created publisher as @publisher" do
        Publisher.stub(:new).with({'these' => 'params'}) { mock_publisher(:save => true) }
        post :create, :publisher => {'these' => 'params'}
        assigns(:publisher).should be(mock_publisher)
      end

      it "redirects to the created publisher" do
        Publisher.stub(:new) { mock_publisher(:save => true) }
        post :create, :publisher => {}
        response.should redirect_to(publisher_url(mock_publisher))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved publisher as @publisher" do
        Publisher.stub(:new).with({'these' => 'params'}) { mock_publisher(:save => false) }
        post :create, :publisher => {'these' => 'params'}
        assigns(:publisher).should be(mock_publisher)
      end

      it "re-renders the 'new' template" do
        Publisher.stub(:new) { mock_publisher(:save => false) }
        post :create, :publisher => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested publisher" do
        Publisher.stub(:find).with("37") { mock_publisher }
        mock_publisher.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :publisher => {'these' => 'params'}
      end

      it "assigns the requested publisher as @publisher" do
        Publisher.stub(:find) { mock_publisher(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:publisher).should be(mock_publisher)
      end

      it "redirects to the publisher" do
        Publisher.stub(:find) { mock_publisher(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(publisher_url(mock_publisher))
      end
    end

    describe "with invalid params" do
      it "assigns the publisher as @publisher" do
        Publisher.stub(:find) { mock_publisher(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:publisher).should be(mock_publisher)
      end

      it "re-renders the 'edit' template" do
        Publisher.stub(:find) { mock_publisher(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested publisher" do
      Publisher.stub(:find).with("37") { mock_publisher }
      mock_publisher.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the publishers list" do
      Publisher.stub(:find) { mock_publisher }
      delete :destroy, :id => "1"
      response.should redirect_to(publishers_url)
    end
  end

end
