require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RegionaltitlesController do

  # This should return the minimal set of attributes required to create a valid
  # Regionaltitle. As you add validations to Regionaltitle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all regionaltitles as @regionaltitles" do
      regionaltitle = Regionaltitle.create! valid_attributes
      get :index
      assigns(:regionaltitles).should eq([regionaltitle])
    end
  end

  describe "GET show" do
    it "assigns the requested regionaltitle as @regionaltitle" do
      regionaltitle = Regionaltitle.create! valid_attributes
      get :show, :id => regionaltitle.id.to_s
      assigns(:regionaltitle).should eq(regionaltitle)
    end
  end

  describe "GET new" do
    it "assigns a new regionaltitle as @regionaltitle" do
      get :new
      assigns(:regionaltitle).should be_a_new(Regionaltitle)
    end
  end

  describe "GET edit" do
    it "assigns the requested regionaltitle as @regionaltitle" do
      regionaltitle = Regionaltitle.create! valid_attributes
      get :edit, :id => regionaltitle.id.to_s
      assigns(:regionaltitle).should eq(regionaltitle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Regionaltitle" do
        expect {
          post :create, :regionaltitle => valid_attributes
        }.to change(Regionaltitle, :count).by(1)
      end

      it "assigns a newly created regionaltitle as @regionaltitle" do
        post :create, :regionaltitle => valid_attributes
        assigns(:regionaltitle).should be_a(Regionaltitle)
        assigns(:regionaltitle).should be_persisted
      end

      it "redirects to the created regionaltitle" do
        post :create, :regionaltitle => valid_attributes
        response.should redirect_to(Regionaltitle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved regionaltitle as @regionaltitle" do
        # Trigger the behavior that occurs when invalid params are submitted
        Regionaltitle.any_instance.stub(:save).and_return(false)
        post :create, :regionaltitle => {}
        assigns(:regionaltitle).should be_a_new(Regionaltitle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Regionaltitle.any_instance.stub(:save).and_return(false)
        post :create, :regionaltitle => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested regionaltitle" do
        regionaltitle = Regionaltitle.create! valid_attributes
        # Assuming there are no other regionaltitles in the database, this
        # specifies that the Regionaltitle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Regionaltitle.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => regionaltitle.id, :regionaltitle => {'these' => 'params'}
      end

      it "assigns the requested regionaltitle as @regionaltitle" do
        regionaltitle = Regionaltitle.create! valid_attributes
        put :update, :id => regionaltitle.id, :regionaltitle => valid_attributes
        assigns(:regionaltitle).should eq(regionaltitle)
      end

      it "redirects to the regionaltitle" do
        regionaltitle = Regionaltitle.create! valid_attributes
        put :update, :id => regionaltitle.id, :regionaltitle => valid_attributes
        response.should redirect_to(regionaltitle)
      end
    end

    describe "with invalid params" do
      it "assigns the regionaltitle as @regionaltitle" do
        regionaltitle = Regionaltitle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Regionaltitle.any_instance.stub(:save).and_return(false)
        put :update, :id => regionaltitle.id.to_s, :regionaltitle => {}
        assigns(:regionaltitle).should eq(regionaltitle)
      end

      it "re-renders the 'edit' template" do
        regionaltitle = Regionaltitle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Regionaltitle.any_instance.stub(:save).and_return(false)
        put :update, :id => regionaltitle.id.to_s, :regionaltitle => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested regionaltitle" do
      regionaltitle = Regionaltitle.create! valid_attributes
      expect {
        delete :destroy, :id => regionaltitle.id.to_s
      }.to change(Regionaltitle, :count).by(-1)
    end

    it "redirects to the regionaltitles list" do
      regionaltitle = Regionaltitle.create! valid_attributes
      delete :destroy, :id => regionaltitle.id.to_s
      response.should redirect_to(regionaltitles_url)
    end
  end

end
