require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SupplierdiscountsController do

  def mock_supplierdiscount(stubs={})
    @mock_supplierdiscount ||= mock_model(Supplierdiscount, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all supplierdiscounts as @supplierdiscounts" do
      Supplierdiscount.stub(:all) { [mock_supplierdiscount] }
      get :index
      assigns(:supplierdiscounts).should eq([mock_supplierdiscount])
    end
  end

  describe "GET show" do
    it "assigns the requested supplierdiscount as @supplierdiscount" do
      Supplierdiscount.stub(:find).with("37") { mock_supplierdiscount }
      get :show, :id => "37"
      assigns(:supplierdiscount).should be(mock_supplierdiscount)
    end
  end

  describe "GET new" do
    it "assigns a new supplierdiscount as @supplierdiscount" do
      Supplierdiscount.stub(:new) { mock_supplierdiscount }
      get :new
      assigns(:supplierdiscount).should be(mock_supplierdiscount)
    end
  end

  describe "GET edit" do
    it "assigns the requested supplierdiscount as @supplierdiscount" do
      Supplierdiscount.stub(:find).with("37") { mock_supplierdiscount }
      get :edit, :id => "37"
      assigns(:supplierdiscount).should be(mock_supplierdiscount)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created supplierdiscount as @supplierdiscount" do
        Supplierdiscount.stub(:new).with({'these' => 'params'}) { mock_supplierdiscount(:save => true) }
        post :create, :supplierdiscount => {'these' => 'params'}
        assigns(:supplierdiscount).should be(mock_supplierdiscount)
      end

      it "redirects to the created supplierdiscount" do
        Supplierdiscount.stub(:new) { mock_supplierdiscount(:save => true) }
        post :create, :supplierdiscount => {}
        response.should redirect_to(supplierdiscount_url(mock_supplierdiscount))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved supplierdiscount as @supplierdiscount" do
        Supplierdiscount.stub(:new).with({'these' => 'params'}) { mock_supplierdiscount(:save => false) }
        post :create, :supplierdiscount => {'these' => 'params'}
        assigns(:supplierdiscount).should be(mock_supplierdiscount)
      end

      it "re-renders the 'new' template" do
        Supplierdiscount.stub(:new) { mock_supplierdiscount(:save => false) }
        post :create, :supplierdiscount => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested supplierdiscount" do
        Supplierdiscount.stub(:find).with("37") { mock_supplierdiscount }
        mock_supplierdiscount.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :supplierdiscount => {'these' => 'params'}
      end

      it "assigns the requested supplierdiscount as @supplierdiscount" do
        Supplierdiscount.stub(:find) { mock_supplierdiscount(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:supplierdiscount).should be(mock_supplierdiscount)
      end

      it "redirects to the supplierdiscount" do
        Supplierdiscount.stub(:find) { mock_supplierdiscount(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(supplierdiscount_url(mock_supplierdiscount))
      end
    end

    describe "with invalid params" do
      it "assigns the supplierdiscount as @supplierdiscount" do
        Supplierdiscount.stub(:find) { mock_supplierdiscount(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:supplierdiscount).should be(mock_supplierdiscount)
      end

      it "re-renders the 'edit' template" do
        Supplierdiscount.stub(:find) { mock_supplierdiscount(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested supplierdiscount" do
      Supplierdiscount.stub(:find).with("37") { mock_supplierdiscount }
      mock_supplierdiscount.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the supplierdiscounts list" do
      Supplierdiscount.stub(:find) { mock_supplierdiscount }
      delete :destroy, :id => "1"
      response.should redirect_to(supplierdiscounts_url)
    end
  end

end
